package service

import "errors"

var (
	ErrUsernameTaken          = errors.New("username already taken")
	ErrReminderChannelMissing = errors.New("at least one enabled reminder channel is required")
	ErrInvalidTime            = errors.New("invalid time format, expected RFC3339")
	ErrInvalidCredentials     = errors.New("invalid username or password")
	ErrInvalidOldPassword     = errors.New("invalid old password")
	ErrUserNotFound           = errors.New("user not found")
	ErrTagNameEmpty           = errors.New("tag name cannot be empty")
	ErrInvalidTagColor        = errors.New("invalid tag color, expected #RRGGBB hex")
	ErrInvalidTagIcon         = errors.New("invalid tag icon, must be in the curated list")
	ErrUnknownTag             = errors.New("task references a tag that does not exist for this user")
	ErrConfigKeyUnknown       = errors.New("unknown config key")
	ErrConfigKeyLocked        = errors.New("config key is read-only")
	ErrConfigValueInvalid     = errors.New("invalid config value")
	ErrEmailNotConfigured     = errors.New("email service is not configured")
	ErrCodeCooldown           = errors.New("please wait before requesting another code")
	ErrCodeNotFound           = errors.New("verification code not found or already used")
	ErrCodeExpired            = errors.New("verification code has expired")
	ErrCodeAttemptsExceeded   = errors.New("too many verification attempts")
	ErrCodeInvalid            = errors.New("invalid verification code")
	ErrEmailAlreadyTaken      = errors.New("email is already registered")
	ErrLastAuthMethod         = errors.New("cannot unlink the last authentication method")
	ErrOAuthAlreadyLinked     = errors.New("this OAuth account is already linked")
	ErrOAuthLinkedToOther     = errors.New("this OAuth account is linked to another user")
	ErrOAuthAccountNotFound   = errors.New("OAuth account not found")
)
